### ISSUE TITLE
Errors solved

### ISSUE THREAD

**Issue by Krishjain2911** [aquasecurity/Hacktoberfest#14]
What is the title of your production?

What category best describes this content? (see [here](/Readme.md#external-contributions) for explanation)
Introduction / Review / Tutorial / Case study 

What kind of media you are producing?
Written article (or blog post) / Video / Podcast / else (Detailed)

How will your work be viewable to the world? Where are you going to post it? (e.g YouTube, Medium, Company blog, Personal blog, twitch, etc.)

Additional information:

**Comment by itaysk** [comment]
@Krishjain2911 it's unclear what this issue is about. I'm going to close this but feel free to reopen if needed
