### ISSUE TITLE
Review of Trivy compared to Anchor-Engine and Clair

### ISSUE THREAD

**Issue by AlfredoPardo** [aquasecurity/Hacktoberfest#24]
**What is the title of your production?**
Docker Image Security: Static Analysis Tool Comparison – Anchore Engine vs Clair vs Trivy

**What category best describes this content?** 
Review

**What kind of media you are producing?**
Written article

**How will your work be viewable to the world?**
It is currently in my personal blog: https://www.a10o.net/devsecops/docker-image-security-static-analysis-tool-comparison-anchore-engine-vs-clair-vs-trivy/

**Additional information:**
You can find additional information on how to run these tools in my GitHub: https://github.com/AlfredoPardo/devsecops/tree/master/container_static_analysis

**Comment by itaysk** [comment]
Thank you. you can go ahead and make a PR to contrib-content.md (please mention this issue).

**Comment by AlfredoPardo** [comment]
> Thank you. you can go ahead and make a PR to contrib-content.md (please mention this issue).

Thank you! I've created a pull request for issues from 24 to 28.
