### ISSUE TITLE
Submitting Kube-Bench Information to Apache Superset (PostgreSQL)

### ISSUE THREAD

**Issue by AlfredoPardo** [aquasecurity/Hacktoberfest#26]
**Please describe the integration you propose**:
The purpose of this script is to parse Kube-bench's master and worker node outputs and submit them to a PostgreSQL Database to be used in Apache Superset

**What are you integrating with?**
Apache Superset

**Please a link to the other party's repository or website**:
The demo of this script in action can be seen here: https://youtu.be/Mp8ruNtx_HY?t=1949

**Where are you going to implement this integration?**
https://github.com/AlfredoPardo/devsecops/blob/master/kubernetes-configurations/kube-bench-to-superset.py

**Comment by itaysk** [comment]
Thank you! please go ahead and make a PR to contrib-integrations.md, then I will mark the PR with the hacktoberfest-accepted label
