### ISSUE TITLE
Producing an HTML Report from Trivy

### ISSUE THREAD

**Issue by AlfredoPardo** [aquasecurity/Hacktoberfest#27]
**Please describe the integration you propose**:
The purpose of this script is to parse trivy's output and produce an HTML report using pyjade and jinja2

**What are you integrating with?**
Pyjade and Jinja2 for an HTML report

**Please a link to the other party's repository or website**:

**Where are you going to implement this integration?**
The script is hosted [here](https://github.com/AlfredoPardo/python-for-devsecops/blob/main/analyzing-processing-transforming/html_report.py) and the template [here](https://github.com/AlfredoPardo/python-for-devsecops/blob/main/analyzing-processing-transforming/templates/trivy_report.jade)

**Comment by itaysk** [comment]
Thank you! please go ahead and make a PR to contrib-integrations.md, then I will mark the PR with the hacktoberfest-accepted label
