### ISSUE TITLE
Summarizing Trivy's findings with Pandas and Matplolib

### ISSUE THREAD

**Issue by AlfredoPardo** [aquasecurity/Hacktoberfest#28]
**Please describe the integration you propose**:
This python scripts uses matplotlib and pandas to summarize trivy's output and produce a png file with a pie chart with findings grouped by severity.

**What are you integrating with?**
Matplotlib and Pandas (Python) to produce a pie chart of findings

**Where are you going to implement this integration?**
https://github.com/AlfredoPardo/python-for-devsecops/blob/main/analyzing-processing-transforming/process_data.py

**Comment by itaysk** [comment]
Thank you! please go ahead and make a PR to contrib-integrations.md, then I will mark the PR with the hacktoberfest-accepted label
