### ISSUE TITLE
Issues with links in contrib-content.md and contrib-integrations.md files

### ISSUE THREAD

**Issue by nightlark** [aquasecurity/Hacktoberfest#6]
The initial contrib-content.md and contrib-integrations.md files have a few issues with broken links.

They are:
- The anchor link to the external contributions section of the readme is broken (it has an extra .md at the end of the link)
- The example links are to files that don't exist when they appear to be meant to link to the file being looked at
- The table header that links to the help section of the readme with  the list of repositories to focus only has the last word ('projects') clickable as a link

**Comment by lizrice** [comment]
Fixed by #7
