### ISSUE TITLE
Adding badges in Readme.md

### ISSUE THREAD

**Issue by AshishMhrzn10** [aquasecurity/Hacktoberfest#8]
I would like to add some badges like hacktoberfest, opensource in readme,md to make it a bit more beautiful.

**Comment by sasha27** [comment]
@AshishMhrzn10 has this been picked up? If not then I can look into it!

**Comment by AshishMhrzn10** [comment]
@sasha27 Sorry,  I worked on it.

**Comment by itaysk** [comment]
Thanks but we don't need any badges in this project.
